name: Run Tests

on: [push, pull_request]

jobs:
  test-local:
    runs-on: ubuntu-latest
    name: "Test: Local Python"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run local tests
      run: |
        python -m pytest tests/ -v --alluredir=allure-results-local

  test-docker:
    runs-on: ubuntu-latest
    name: "Test: Docker Container"
    needs: test-local  # waits for local tests to finish

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t qa-tests .

    - name: Run Docker tests
      run: |
        docker run --rm qa-tests python -m pytest tests/ -v --alluredir=allure-results-docker

  upload-results:
    runs-on: ubuntu-latest
    name: "Upload Results"
    needs: [test-local, test-docker]  # Ждет оба job
    if: always()  # Выполнится даже если тесты упали

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Upload combined results
      uses: actions/upload-artifact@v4
      with:
        name: combined-test-results
        path: |
          allure-results-local/
          allure-results-docker/
        retention-days: 30

    - name: Test summary
      run: |
        echo "🎉 CI/CD Pipeline Completed!"
        echo "📊 Local Python tests: ${{ needs.test-local.result }}"
        echo "🐳 Docker tests: ${{ needs.test-docker.result }}"
        echo "📁 Results saved as artifacts"